### ISSUE TITLE
Error with SIP + Asterisk

### ISSUE THREAD

**Issue by lfdominguez** [jitsi/jigasi#100]
Hello i configured Asterisk + pjSIP with an account for jigasi, but when I run jigasi this is the errors in log:

```
May 09, 2018 3:13:30 PM net.java.sip.communicator.util.Logger error
SEVERE: couldn't find a ProtocolProviderServiceSipImpl to dispatch to
May 09, 2018 3:13:33 PM net.java.sip.communicator.util.Logger info
INFO: Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource to: /10.11.0.35:5061
May 09, 2018 3:13:33 PM net.java.sip.communicator.util.Logger error
SEVERE: no listeners
May 09, 2018 3:13:33 PM net.java.sip.communicator.util.Logger error
SEVERE: couldn't find a ProtocolProviderServiceSipImpl to dispatch to
May 09, 2018 3:13:34 PM net.java.sip.communicator.util.Logger info
INFO: Info from the JAIN-SIP stack: Setting SIPMessage peerPacketSource to: /10.11.0.35:5061
May 09, 2018 3:13:34 PM net.java.sip.communicator.util.Logger error
SEVERE: no listeners
May 09, 2018 3:13:34 PM net.java.sip.communicator.util.Logger error
SEVERE: couldn't find a ProtocolProviderServiceSipImpl to dispatch to
```
And Asterisk register and unregister the user

```
 == Contact jitsi/sip:jitsi@10.11.0.11:5060;transport=udp;registering_acc=sip_mtz_desoft_cu has been deleted
    -- Added contact 'sip:jitsi@10.11.0.11:5060;transport=udp;registering_acc=sip_mtz_desoft_cu' to AOR 'jitsi' with expiration of 600 seconds
  == Contact jitsi/sip:jitsi@10.11.0.11:5060;transport=udp;registering_acc=sip_mtz_desoft_cu has been created
  == Endpoint jitsi is now Reachable
    -- Contact jitsi/sip:jitsi@10.11.0.11:5060;transport=udp;registering_acc=sip_mtz_desoft_cu is now Unreachable.  RTT: 0.000 msec
  == Endpoint jitsi is now Unreachable
```

**Comment by damencho** [comment]
Hey, @lfdominguez can you share your configuration of jigasi, the sip-communicator.properties file?
I've been testing jigasi these days and have no problem registering to asterisk and making calls.

**Comment by damencho** [comment]
You cannot use focus user for jigas, this can lead to unpredictable results, change that and try again.

**Comment by lfdominguez** [comment]
ummm .. i need to create a new user for jigasi??

**Comment by damencho** [comment]
Donyou actually need one? Have you enabled authentication ob your deployment? This is needed if you have authentication enabled.

**Comment by lfdominguez** [comment]
yeap i need authentication because is the main OpenFire of my network

**Comment by damencho** [comment]
So you need another user for jigasi.

**Comment by lfdominguez** [comment]
i will test that

**Comment by lfdominguez** [comment]
Same error......
[asterisk.log](https://github.com/jitsi/jigasi/files/2013798/asterisk.log)
[jigasi.log](https://github.com/jitsi/jigasi/files/2013799/jigasi.log)

**Comment by damencho** [comment]
It seems to me the incoming sip messages cannot be matched to the sip protocol provider. 
This is where it is matched: https://github.com/jitsi/jitsi/blob/288c1a135b3391585f8f6fe56306487d4b55f3ae/src/net/java/sip/communicator/impl/protocol/sip/SipStackSharing.java#L903
In your asterisk config are you using the account peer that is registered to send the calls or you are just sending the sip to the jigasi machine using its ip and port, the second approach will not work?

**Comment by lfdominguez** [comment]
Well, my asterisk has 2 interfaces, one public and one privated, i configure static that PJSIP listen only in the public iface (that one connect to jigasi) and now works!!!!!!! reading the asterisk logs, sems that asterisk catch de private IP as public and when jigasi try connect, asterisk respond with a wrong public IP, i dont know why.....

Thanks for let me see the problem.....

**Comment by fuqiangleon** [comment]
@damencho  hope to ask you a question: how can i config the SIP port  if we used a different port ,eg:6060 .

tks.

**Comment by damencho** [comment]
@fuqiangleon Can you ask your questions on the community forum and not post on random issues that has nothing to do with your question. Thank you.
