### ISSUE TITLE
Issue with browser yandex

### ISSUE THREAD

**Issue by dquangsinh** [jitsi/jigasi#143]
Hi, i try open on browser yandex, it not working

and this error on js

Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Logger.js:88
_.web.js:5 Uncaught ReferenceError: JitsiMeetJS is not defined
    at Object.<anonymous> (_.web.js:5)

**Comment by damencho** [comment]
This browser haven't been tested so it is possible to have some issues. 
Looking at the error seems like lib-jitsi-meet is not loaded. Are you testing on meet.jit.si.
I'm closing this as it has nothing to do with jigasi.

Please in the future when you have problems or questions, discuss them first at the community forum prior opening an issue in various projects. Thanks.
