### ISSUE TITLE
How to configure stun 

### ISSUE THREAD

**Issue by devamitmehra** [jitsi/jigasi#147]
There is any way to use Stun , turn with jigasi ,
As i am facing the issue with NAT configuration issue is (when incoming call come from free switch it is not responding at all)
Thanks in advance !!!

**Comment by damencho** [comment]
No, jigasi cannot use stun/turn. Jigasi acts as a client and expects the server to use latching for the media. Have you enabled that in freeswitch?

Please, when you have questions or problems write to the community forum first, before opening issues.

**Comment by damencho** [comment]
https://freeswitch.org/confluence/display/FREESWITCH/Proxy+Media#ProxyMedia-Howtoenableit

**Comment by creativeguitar** [comment]
Latching helps but its not a great solution. When phone user connects to the room, all the packets that the user sends are lost until someone in the room unmutes their mic and generates traffic from within the room. Is there any other solution?

**Comment by damencho** [comment]
This means there is a bug, we are sending few packets (hole punch packets) so we can open the communication between jigasi and the sip server ... There is no option for using stun. 
By default we send [3 packets](https://github.com/jitsi/jitsi/blob/master/src/net/java/sip/communicator/service/protocol/media/TransportManager.java#L108), maybe try increasing that using this property and see whether it helps: net.java.sip.communicator.impl.protocol.HOLE_PUNCH_PKT_COUNT
https://github.com/jitsi/jitsi/blob/master/src/net/java/sip/communicator/service/protocol/media/TransportManager.java#L102

**Comment by creativeguitar** [comment]
Incrementing the packet count to 10 did not help

`Jigasi 2020-04-27 16:36:08.929 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() net.java.sip.communicator.impl.protocol.HOLE_PUNCH_PKT_COUNT=10`


here is my log 

`INFO: [76] org.jitsi.jigasi.SipGateway.incomingCallReceived().188 Incoming call received...
INFO: [77] org.jitsi.jigasi.SipGatewaySession.run().1281 [ctx=15880234507611019853068] Wait thread cancelled
INFO: [76] org.jitsi.jigasi.JvbConference.setXmppProvider().539 [ctx=15880234507611019853068] Using ProtocolProviderServiceJabberImpl(Jabber:352e067b@meet.jitsi/352e067b)
INFO: [78] impl.protocol.jabber.OperationSetBasicTelephonyJabberImpl.registrationStateChanged().125 Jingle : ON
INFO: [78] org.jitsi.jigasi.JvbConference.registrationStateChanged().577 [ctx=15880234507611019853068] Registering XMPP.
INFO: [78] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.authenticated().2535 Authenticated: false
INFO: [78] org.jitsi.jigasi.JvbConference.joinConferenceRoom().648 [ctx=15880234507611019853068] Joining JVB conference room: test@muc.meet.jitsi
INFO: [84] impl.protocol.jabber.ChatRoomJabberImpl.joined().1256 test@muc.meet.jitsi/focus has joined the test@muc.meet.jitsi chat room.
INFO: [84] impl.protocol.jabber.ChatRoomJabberImpl.joined().1256 test@muc.meet.jitsi/137eb503 has joined the test@muc.meet.jitsi chat room.
INFO: [104] impl.protocol.jabber.IceUdpTransportManager.createIceAgent().346 End gathering harvester within 84 ms
INFO: [104] impl.protocol.jabber.CallPeerMediaHandlerJabberImpl.harvestCandidates().1198 End candidate harvest within 49 ms
INFO: [104] org.jitsi.jigasi.JvbConference.incomingCallReceived().1024 [ctx=15880234507611019853068] Got invite from focus
INFO: [112] service.protocol.media.MediaHandler.registerDynamicPTsWithStream().1003 Dynamic PT map: 126=rtpmap:-1 telephone-event/8000; 111=rtpmap:-1 opus/48000/2 fmtp:useinbandfec=1;minptime=10; 103=rtpmap:-1 unknown/90000;
INFO: [112] service.protocol.media.MediaHandler.registerDynamicPTsWithStream().1020 PT overrides [103->104 ]
INFO: [112] service.protocol.media.CallPeerMediaHandler.start().1961 Starting
INFO: [111] service.protocol.media.MediaHandler.registerDynamicPTsWithStream().1003 Dynamic PT map: 101=rtpmap:-1 telephone-event/8000;
INFO: [111] service.protocol.media.MediaHandler.registerDynamicPTsWithStream().1020 PT overrides []
INFO: [131] org.jitsi.jigasi.SipGatewaySession.handleCallState().1123 [ctx=15880234507611019853068] Sip call IN_PROGRESS: Call: id=15880234506979337317 peers=1
INFO: [131] org.jitsi.jigasi.SipGatewaySession.handleCallState().1132 [ctx=15880234507611019853068] SIP call format used: rtpmap:0 PCMU/8000
INFO: [131] org.jitsi.jigasi.SipGatewaySession.peerStateChanged().1204 [ctx=15880234507611019853068] SIP peer state: Connected
INFO: [131] service.protocol.media.CallPeerMediaHandler.start().1961 Starting
INFO: [131] service.protocol.media.TransportManager.sendHolePunchPacket().552 Send NAT hole punch packets
INFO: [112] org.jitsi.jigasi.JvbConference.callStateChanged().1122 [ctx=15880234507611019853068] JVB conference call IN_PROGRESS.
SEVERE: [132] org.jitsi.jigasi.SipGatewaySession.run().1057 [ctx=15880234507611019853068] Stopped receiving RTP for Call: id=15880234506979337317 peers=1`

**Comment by damencho** [comment]
We haven't seen problems with latching for years ... what is the sip server do you know?

**Comment by creativeguitar** [comment]
Asterisk and I have full control. I pasted the configs below.

```
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[endpoint_internal](!)
type=endpoint
context=from-internal
disallow=all
allow=ulaw

[6000]
type=endpoint
transport=transport-udp
context=from-internal
disallow=all
allow=ulaw
auth=6000
aors=6000
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
ice_support=yes

[6000]
type=auth
auth_type=userpass
password=6000
username=6000

[6000]
type=aor
max_contacts=2
remove_existing=yes

```

**Comment by damencho** [comment]
Add to your endpoint for jigasi nat=force_rport,comedia

**Comment by damencho** [comment]
```
;   nat = comedia           ; Send media to the port Asterisk received it from regardless
;                           ; of where the SDP says to send it.
```

**Comment by creativeguitar** [comment]
it didn't work. for what I am reading nat is a sip.conf option. I am on Asterisk 17 and it uses PJSIP

In chan_pjsip, the endpoint options that control NAT behavior are:

rtp_symmetric - Send media to the address and port from which Asterisk receives it, regardless of where SDP indicates that it should be sent
force_rport - Send responses to the source IP address and port as though port were present, even if it's not
rewrite_contact - Rewrite SIP Contact to the source address and port of the request so that subsequent requests go to that address and port.

I think it latching. Otherwise when I unmute the mic from within the room I will still have 1 way audio. However, when I unmute the mic, it latches to the public IP address and everything works great.

**Comment by TBG-FR** [comment]
Have you managed to fix your issue ?

**Comment by TBG-FR** [comment]
This could help you, if you're facing the same issue : https://freeswitch.org/confluence/display/FREESWITCH/NAT+Traversal#NATTraversal-NDLB-connectile-dysfunction
