### ISSUE TITLE
How can I access the SIP URI for an inbound call?

### ISSUE THREAD

**Issue by extremerotary** [jitsi/jigasi#151]
Hey guys,
I'm trying to capture the SIP URI in the "from" header (or RPID) for an inbound call to Jigasi so I can parse out the caller ID number to display the caller ID Name and caller ID number in the Jitsi interface when a SIP caller dials into the meeting. Is the "from" SIP URI published from Jigasi to Jitsi? In my configuration, Jigasi is on a separate physical server than Jitsi-Meet. 
I checked the community, but didn't see anything this specific, though I did see some references to the URI being accessible. I appreciate any guidance you can provide on how I can access the "from" URI. Thanks.

**Comment by damencho** [comment]
Please use the community forum for problems or questions before opening new issues.

What I see is that we push displayname to jitsi-meet:
https://github.com/jitsi/jigasi/blob/ee4b91c8e748d5d41139fe9cf8e1ed91b736abd4/src/main/java/org/jitsi/jigasi/JvbConference.java#L651
