### ISSUE TITLE
Jigasi Installation Error : Compilation Error

### ISSUE THREAD

**Issue by premanandmanimaran** [jitsi/jigasi#160]
Hello I am trying to Install Jigasi in My own Jitsi Server in AWS. I followed the instruction and dont know what is wrong. I am trying to implement Transcribe feature.

1. Checkout latest source:
git clone https://github.com/jitsi/jigasi.git
(No ERROR)
Build:
2. cd jigasi
mvn install -Dassembly.skipAssembly=false
(ERROR)

[WARNING] The POM for org.jitsi:jitsi-videobridge:jar:1.0-20160202.163439-54 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jigasi ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ jigasi ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 60 source files to /jigasi/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.404 s
[INFO] Finished at: 2019-03-12T08:58:13Z
[INFO] Final Memory: 21M/396M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project jigasi: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by damencho** [comment]
> [ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?

Your error says it all. 

Please use the community forum for questions or problems before opening new issues.
