### ISSUE TITLE
how to configure google speech to text

### ISSUE THREAD

**Issue by smilence86** [jitsi/jigasi#188]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
--- I want to show subtitles on clients with google speech2text.I use https://github.com/jitsi/docker-jitsi-meet to deploy on my machine, git clone it and switched dev branch and replaced "image: jitsi/" with "build: " in *.yml files, run command "docker-compose -f docker-compose.yml -f jigasi.yml up -d --force-recreate" to start, but I found there is not gcloud installed in the jigasi container, so I "docker exec" in it and install gcloud, init google account, and now I have no ideas how to do, there is no detail docs in readme file, please help me, thanks!

## Current behavior
---Nothine happened when I click "cc" button on web client.

## Expected Behavior
---hope show subtitles from others realtime

## Possible Solution
---I don't know how to configure google speech2text api, 

## Steps to reproduce
---

# Environment details
---https://github.com/jitsi/docker-jitsi-meet

**Comment by nikvaessen** [comment]
I'm unaware of the current state of docker support for Jitsi Meet. At the time it was a side-project by one of our developers @saghul. The most likely cause is that the configuration inside the Jigasi docker container not set up for speech-to-text. The hint I can give you currently is to look around for the `sip-communicator.properties` file inside the container and make sure it contains all the properties required for the speech-to-text use case.

**Comment by saghul** [comment]
You can follow this PR, which adds support for the transcribing options to the Docker setup: https://github.com/jitsi/docker-jitsi-meet/pull/59

**Comment by smilence86** [comment]
@nikvaessen Thanks for your reply, I don't know which properties are required for speech2text. To use speech2text need modify code? or configure only?

I have already added these properties below to ~/.jitsi-meet-cfg/jigasi/sip-communicator.properties:

1. org.jitsi.jigasi.transcription.ENABLE_TRANSLATION=true
2. org.jitsi.jigasi.ENABLE_SIP=true

The translate feature I need too.  
In jigasi container, the file is /config/sip-communicator.properties.

Unfortunately, It's not work. I think something missed I have, or did wrong.

Then, I'm going to modify docker-jitsi-meet/jigasi/Dockerfile, let installation from source code instead of apt repository, ensure the code is newest which contain google speech to text api's caller.

**Comment by smilence86** [comment]
@saghul Thanks for your project docker-jitsi-meet, I need two features which are speech to text and translate, not transcribing. I plan to use docker image named "google/cloud-sdk:latest" directly, then install jigasi from source code to integrate google speech to text.
  
I found another problem yet, It seems that web client not integrate subtitles feature, nothing happened when I click "cc" button, no logs output in chrome dev tool console as well.

**Comment by saghul** [comment]
The PR is only about transcribing IIRC. If more options are required, it can be done in follow-up PRs. I'm pretty swamped at the moment and haven't been able to work on it lately.

**Comment by smilence86** [comment]
@saghul I think it's not enough just add some options only, The jigasi container's environment doesn't have gcloud tool. It's necessary to change base image of jigasi to support it.

**Comment by smilence86** [comment]
I'm try to install docker jigasi from source code, Dockerfile like this:

```FROM google/cloud-sdk:latest

RUN uname -a && cat /etc/issue

RUN apt update && apt install wget openjdk-8-jdk maven unzip -y

RUN java -version
RUN mvn -version
WORKDIR /usr/src/


RUN wget https://github.com/jitsi/jigasi/archive/245.tar.gz
RUN tar zxf 245.tar.gz && ls -l && cd ./jigasi-245 && ls -l && mvn install "-Dassembly.skipAssembly=false" -T4 \
&& ls -l && cd ./target/ && ls -l && unzip jigasi-linux-x64-1.1-SNAPSHOT.zip && ls -l && cd ./jigasi-linux-x64-1.1-SNAPSHOT && ls -l 

COPY jigasi.sh /usr/src/jigasi-245/target/jigasi-linux-x64-1.1-SNAPSHOT/

COPY rootfs/ /
VOLUME /config

RUN cd /usr/src/jigasi-245/target/jigasi-linux-x64-1.1-SNAPSHOT/ && ls -l && cat jigasi.sh && ./jigasi.sh --domain=t.meeting.cgland.top --subdomain=focus --secret=s3cr37
```

but failed as well, output logs shows jigasi try to connect domain:5347, I don't know where is use this port. error is:
org.jitsi.meet.ComponentMain.call().299 java.net.SocketTimeoutException: connect timed out, host:my domain, port:5347

**Comment by nikvaessen** [comment]
You should probably move this discussion to the community forum.

**Comment by netaskd** [comment]
@smilence86 
The PR jitsi/docker-jitsi-meet#59 doing both - transcribing and cc (speech2text in subtitles) by default.
For cc used `org.jitsi.jigasi.transcription.SEND_JSON=true`

**Comment by smilence86** [comment]
@netaskd Thanks for your reply, I have done, In addition, My partner added two buttons on web page to switch speech language and translate language with these two console commands:
  
`APP.conference._room.setLocalParticipantProperty('transcription_language','ja-JP');
  
APP.conference._room.setLocalParticipantProperty('translation_language','zh-cn');`

But the accuracy is not enough to use, As same as google's production(APIs), the accuracy less than google translate app.

**Comment by netaskd** [comment]
@smilence86 could you make a PR for this property?

**Comment by smilence86** [comment]
@netaskd Sorry, That's not my work, I don't know about react at all. It's need to modify project jitsi-meet. Anyone who know react could do it. Just looks like this:

![image](https://user-images.githubusercontent.com/6102831/62760749-49b6a980-bab7-11e9-835f-771bbf3f341b.png)
![image](https://user-images.githubusercontent.com/6102831/62761186-8df67980-bab8-11e9-9a03-56df9c075598.png)

**Comment by smilence86** [comment]
I tried to use google speech to text api that could detecting language spoken automatically: [.](https://cloud.google.com/speech-to-text/docs/multiple-languages), So no need speech language button, Unfortunately, The accuracy is more worse, give up.
