### ISSUE TITLE
Jitsi-Conference-Room Header does not work

### ISSUE THREAD

**Issue by himpierre** [jitsi/jigasi#216]
## Description
Hi Devs. I'm trying to use jigasi to dial in to a jitsi conference but to no avail.

```
  == Using SIP RTP CoS mark 5
    -- Executing [503@local:1] SIPAddHeader("SIP/501-00000002", "Jitsi-Conference-Room: myroom") in new stack
    -- Executing [503@local:2] Dial("SIP/501-00000002", "SIP/503") in new stack
  == Using SIP RTP CoS mark 5
    -- Called SIP/503
    -- SIP/503-00000003 is ringing
    -- SIP/503-00000003 is ringing
    -- Got SIP response 486 "Busy here" back from 
```
Jigasi logs:

```
Jigasi 2020-01-02 13:24:23.078 INFO: [692] org.jitsi.jigasi.SipGateway.incomingCallReceived().188 Incoming call received...
Jigasi 2020-01-02 13:24:24.081 INFO: [693] org.jitsi.jigasi.SipGatewaySession.run().1096 No JVB room name provided in INVITE header
```

---

## Current behavior
Jigasi does not answer the call.

---

## Expected Behavior
Jigasi answers the call.

---

Any hints how to solve this?

Cheers, t.

**Comment by himpierre** [comment]
Hm. It Seems the correct header is now "Room-Name"?

**Comment by damencho** [comment]
`Jitsi-Conference-Room` is the default header name. Can you show complete logs of such a call?

**Comment by damencho** [comment]
Please use the community forum for asking questions before opening new issues!

**Comment by himpierre** [comment]
I was able to solve the problem by myself. See https://community.jitsi.org/t/solved-jigasi-java-lang-nullpointerexception/21291

cheers, t.
