### ISSUE TITLE
jigasi hangs up after 30s

### ISSUE THREAD

**Issue by himpierre** [jitsi/jigasi#220]
## Description
I configured jigasi to route sip calls to conferences. Everything works but after 30s jigasi hangs up. This happens on two different setups to me. Here is what the logs says last,

```
2020-01-10 17:40:02.708 INFO: [25110] service.protocol.media.TransportManager.sendHolePunchPacket().552 Send NAT hole punch packets
2020-01-10 17:40:02.789 INFO: [110] org.jitsi.jigasi.JvbConference.callStateChanged().1111 [ctx=15786780011031924958308] JVB conference call IN_PROGRESS.
2020-01-10 17:40:34.587 INFO: [7264] org.jitsi.jigasi.SipGatewaySession.handleCallState().1138 [ctx=15786780011031924958308] SIP call ended: CallPeerChangeEvent: type=CallPeerStatusChange oldV=net.java.sip.communicator.service.protocol.CallPeerState:Connected newV=net.java.sip.communicator.service.protocol.CallPeerState:Failed for peer=3057707074 <30xxxxxxxxx@xx.xx.xx.xx>;status=Failed
2020-01-10 17:40:34.604 INFO: [7264] org.jitsi.jigasi.SipGatewaySession.peerStateChanged().1204 [ctx=15786780011031924958308] SIP peer state: Failed
```
The strange thing is it happens always after 30s. Last words from asterisk:

```
User-Agent: Jigasi1.1.45-g7ca838dLinux
Reason: SIP;cause=408;text="The remote party has not replied!The call will be disconnected"
Content-Length: 0
```

---

## Current behavior

Jigasi hangs up.
---

## Expected Behavior

Call is stable.

---

## Possible Solution
---

## Steps to reproduce
---

# Environment details
```
root@meetings:/# dpkg -l | grep jitsi
ii  jitsi-meet                     1.0.4153-1                        all          WebRTC JavaScript video conferences
ii  jitsi-meet-prosody             1.0.3775-1                        all          Prosody configuration for Jitsi Meet
ii  jitsi-meet-web                 1.0.3775-1                        all          WebRTC JavaScript video conferences
ii  jitsi-meet-web-config          1.0.3775-1                        all          Configuration for web serving of Jitsi Meet
ii  jitsi-videobridge              1126-1                            amd64        WebRTC compatible Selective Forwarding Unit (SFU)
root@meetings:/# dpkg -l | grep jigasi
ii  jigasi                         1.1-45-g7ca838d-1                 amd64        Jitsi Gateway for SIP
root@meetings:/# 
```

---

**Comment by damencho** [comment]
This seems like the call was dropped from asterisk side. Can you upload the /var/log/jitsi content after a failed call as it contains a pcap file with all sip exchanged messages.

**Comment by damencho** [comment]
Nope, its hanguped from jigasi side, need the pcap files to see what is going on.

**Comment by himpierre** [comment]
Thanks for taking care @damencho 

Here the download link to my nextcloud server: https://fluffycloud.de/s/x8nm5adFP4GKZwA

**Comment by damencho** [comment]
Try setting `net.java.sip.communicator.impl.protocol.sip .SKIP_REINVITE_ON_FOCUS_CHANGE_PROP=true` in jigasi config and restart jigasi. Does it change anything? 
Asterisk does not reply to re-invites send from jigasi and this is considered as signaling server gone away. This is visible in the pcap you sent.

**Comment by himpierre** [comment]
This works! Thanks @damencho. I'm going to order a cocktail now. Have a nice evening!

cheers, t.

**Comment by damencho** [comment]
beers on FOSDEM, please 😁

**Comment by yasithph** [comment]
Had the same issue with voximplant and @damencho  solution fixed it.

**Comment by yasithph** [comment]
Had the same issue with voximplant and @damencho 's solution fixed it. @damencho is a life saver

**Comment by fonoempresa** [comment]
I wrote down net.java.sip.communicator.impl.protocol.sip.acc1403273890647.SKIP_REINVITE_ON_FOCUS_CHANGE_PROP=true  in /etc/jitsi/jigasi/sip-communicator.properties file as @damencho suggested. But, I can't make jitsi hang the pone call. SIP user is registered in my Asterisk box, but when i call jistsi extension the call never pass thru

**Comment by 5280designco** [comment]
> net.java.sip.communicator.impl.protocol.sip

Where to I change this?.....
