### ISSUE TITLE
Integrate SIP video in Jitsi Meet

### ISSUE THREAD

**Issue by heutger** [jitsi/jigasi#23]
Is it possible to join a jitsi meeting via SIP not only with audio but also video? Some SIP providers like getonsip, sip2sip, linphone support SIP video, also there are some SIP video implementations via WebRTC, so I wonder, why jitsi meet only supports audio, or is there something to be configured?

**Comment by damencho** [comment]
Answered on the mailinglist.

**Comment by sunshuvo** [comment]
Dear Heutger,
I also need the same badly. Did you find any way to get SIP Video? 
Thank you,

**Comment by joir7** [comment]
> Respondido en la lista de correo.

Good afternoon
We can guide ourselves on how to allow video calls with sip accounts, for now we only manage to make the audio work.
Thank you very much in advance

**Comment by damencho** [comment]
@joir7 Jigasi does not support video and will not support it. It is an audio only component used for dial-in and dial-out.
For sip video calling you can use Jibri.

**Comment by joir7** [comment]
> @joir7 Jigasi does not support video and will not support it. It is an audio only component used for dial-in and dial-out.
> For sip video calling you can use Jibri.

Thank you very much for answering :)
We are having a hard time finding information on how to configure jibri for sip calls, could you indicate an interesting link

**Comment by damencho** [comment]
there is no good doc for it, there are multiple posts in the community forum search there. And there are people implementing it in the moment.
