### ISSUE TITLE
Feature Request: Configurable Jitsi-Conference-Room Header

### ISSUE THREAD

**Issue by jacobsmith** [jitsi/jigasi#246]
Hello,

First, thanks to the whole team - jigasi and jitsi are truly spectacular.

I'm trying to set up incoming calls via Twilio and SIP. I've managed to get everything connected and can call the number and get directed to the default sip room. However, when I try and pass the `Jitsi-Conference-Room` header, Twilio requires custom headers to be prefixed with `X-` for it to be forwarded from their system.

I've been able to confirm this by tailing the pcap files and seeing that headers with `X-` prepended to them are passed on the `INVITE` request, but without the prefix, those headers are not passed.

I don't believe there's any way to customize that header (i.e., change it from `Jitsi-Conference-Room` to `X-Jitsi-Conference-Room`) without modifying the code and recompiling - is that accurate? It's been a while since I've been in Java and not sure if there's a config file somewhere I'm missing.

Thanks

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues.

This is already possible: net.java.sip.communicator.impl.protocol.sip.acc1403273890647.JITSI_MEET_ROOM_HEADER_NAME=X-Room-Name

**Comment by jacobsmith** [comment]
My apologies, @damencho, I didn't see that and wasn't sure if it was a "bug" or not. Much appreciated!
