### ISSUE TITLE
How to configure via telephone (e.g. mute/unmute)?

### ISSUE THREAD

**Issue by Diapolo** [jitsi/jigasi#264]
I couldn't find an answer or a better place, but how can users who joined via telephone mute/unmute? And will telephone users be force-muted by using the mute all switch in the browser? Is there a help-page for this kind of questions ;)?

**Comment by damencho** [comment]
Please when you have questions or problems us the community forum before opening new issues.

By default, you cannot mute jigasi participants and they need to mute from their phone mute button.

**Comment by damencho** [comment]
We are working on adding muting/unmuting through IVR that can be implemented on the sip side.
