### ISSUE TITLE
better document requirements on the SIP side for redirecting SIP calls to specific rooms

### ISSUE THREAD

**Issue by edouardduliege** [jitsi/jigasi#267]
See https://community.jitsi.org/t/configuration-of-a-self-hosted-jitsi-jigasi-for-incoming-calls/31175
It appears that a basic SIP trunk isn't enough to be able to reach a specific conference room by dialing a number. It is unclear what are the requirements on the SIP side.

Being able to set this up would really help small business which would like an open source and self hosted conference service.

**Comment by damencho** [comment]
It is explained that you need to set a custom header to the incoming call. https://github.com/jitsi/jigasi/blob/master/README.md#incoming-calls
