### ISSUE TITLE
SIP registers no call icon

### ISSUE THREAD

**Issue by grego1981** [jitsi/jigasi#270]
Hi all,

I've recently installed and evaluating Jitsi, all is well except from invitation via phone. I have installed jitsi and jigasi via apt using repository. I have configured a SIP account on my asterisk-freepbx server and it registers successfully. 
The process I follow is:
- I create & join a meeting.
- I try to find the call icon on the bottom right but it does not exist
- I use the + icon to invite by phone nothing happens. 
- I try to  call from the invited number, no answer from Jitsi. 

I really do not know how to manipulate the header of the outgoing call to join a meeting so I cannot test properly...

Any help is appreciated!
Thank you!

**Comment by nikvaessen** [comment]
Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.
