### ISSUE TITLE
Call direction

### ISSUE THREAD

**Issue by jbguerraz** [jitsi/jigasi#272]
In order to react to the call direction on xmpp world it would be great to get jigasi passing the information along the presence stanza.

For information, our use case is setting different max occupant limits based on the call direction (like, max 5 slots for incoming calls)

**Comment by damencho** [comment]
But this can be done another way, without this. We have an option to limit number of outgoing calls: https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_filter_iq_rayo.lua#L14
And when jigasi is authenticated with a user "jigasi@auth" you can detect that in prosody and do the count, wouldn't that work also?

**Comment by jbguerraz** [comment]
@damencho  we want to limit number of incoming calls especially.
