### ISSUE TITLE
SIP in jitsi-meet conference does not have any audio/video 

### ISSUE THREAD

**Issue by Farrukh-Haroon** [jitsi/jigasi#28]
I follow the instructions in the quick installation guide, firstly i deployed a jitsi-meet on ubuntu and then the kamailo sip server on the seperate machine and finally the jigasi gateway for sip on the same machine where the jitsi-meet is presence, during jigasi its prompts me the sip account to use for invite the other sip accounts. all things i guess is perfectly deployed. now from the jitsi-meet conference i dialed the sip number registered with the kamailo server get in to the meeting but no media is showing on both sides, what is the problem ?  and how can i dial into the conference from the any sip phone .!
Please any jitsi expert help me out .!

**Comment by damencho** [comment]
https://github.com/jitsi/jigasi/issues/29
