### ISSUE TITLE
java.lang.IllegalArgumentException: masterS.length != saltKeyLength when joining via SIP

### ISSUE THREAD

**Issue by KornKalle** [jitsi/jigasi#286]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---
Jigasi throws an IllegalArgument Exception when SIP Users would join an already existing Room

## Current behavior
---
The moment the call is established following exception occurs and the connection is lost:

> 2020-05-26 10:42:28.554 SEVERE: [130] impl.protocol.sip.CallPeerSipImpl.answer().1339 Failed to create an SDP description for an OK response to an INVITE request!
> java.lang.IllegalArgumentException: masterS.length != saltKeyLength
> 	at org.jitsi.srtp.SrtpContextFactory.<init>(SrtpContextFactory.java:118)
> 	at org.jitsi.impl.neomedia.transform.sdes.SDesTransformEngine.getTransformEngine(SDesTransformEngine.java:150)
> 	at org.jitsi.impl.neomedia.transform.sdes.SDesTransformEngine.update(SDesTransformEngine.java:67)
> 	at org.jitsi.impl.neomedia.transform.sdes.SDesTransformEngine.<init>(SDesTransformEngine.java:48)
> 	at org.jitsi.impl.neomedia.transform.sdes.SDesControlImpl.createTransformEngine(SDesControlImpl.java:122)
> 	at org.jitsi.impl.neomedia.transform.sdes.SDesControlImpl.createTransformEngine(SDesControlImpl.java:34)
> 	at org.jitsi.service.neomedia.AbstractSrtpControl.getTransformEngine(AbstractSrtpControl.java:120)
> 	at org.jitsi.impl.neomedia.MediaStreamImpl.createTransformEngineChain(MediaStreamImpl.java:1232)
> 	at org.jitsi.impl.neomedia.MediaStreamImpl.rtpConnectorChanged(MediaStreamImpl.java:2507)
> 	at org.jitsi.impl.neomedia.MediaStreamImpl.setConnector(MediaStreamImpl.java:2699)
> 	at org.jitsi.impl.neomedia.MediaStreamImpl.<init>(MediaStreamImpl.java:423)
> 	at org.jitsi.impl.neomedia.AudioMediaStreamImpl.<init>(AudioMediaStreamImpl.java:167)
> 	at org.jitsi.impl.neomedia.MediaServiceImpl.createMediaStream(MediaServiceImpl.java:422)
> 	at org.jitsi.impl.neomedia.MediaServiceImpl.createMediaStream(MediaServiceImpl.java:367)
> 	at net.java.sip.communicator.service.protocol.media.MediaHandler.initStream(MediaHandler.java:940)
> 	at net.java.sip.communicator.service.protocol.media.CallPeerMediaHandler.initStream(CallPeerMediaHandler.java:1189)
> 	at net.java.sip.communicator.impl.protocol.sip.CallPeerMediaHandlerSipImpl.createMediaDescriptionsForAnswer(CallPeerMediaHandlerSipImpl.java:832)
> 	at net.java.sip.communicator.impl.protocol.sip.CallPeerMediaHandlerSipImpl.processFirstOffer(CallPeerMediaHandlerSipImpl.java:483)
> 	at net.java.sip.communicator.impl.protocol.sip.CallPeerMediaHandlerSipImpl.processOffer(CallPeerMediaHandlerSipImpl.java:446)
> 	at net.java.sip.communicator.impl.protocol.sip.CallPeerSipImpl.answer(CallPeerSipImpl.java:1325)
> 	at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.answerCallPeer(OperationSetBasicTelephonySipImpl.java:1955)
> 	at org.jitsi.jigasi.CallManager$AnswerCallThread.run(CallManager.java:368)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

## Expected Behavior
---

SIP User should join the room

## Possible Solution
---

I don't know, I found the source code from where the exception comes but I am not able to identify what those keys are.

## Steps to reproduce
---
Install Nginx, lua5.2
Install Jitsi-meet
Install Jigasi
Configure Jigasi with following parameters:

> org.jitsi.jigasi.DEFAULT_JVB_ROOM_NAME=siptest
> net.java.sip.communicator.impl.protocol.SingleCallInProgressPolicy.enabled=false
> net.java.sip.communicator.impl.protocol.sip.SKIP_REINVITE_ON_FOCUS_CHANGE_PROP=true
> net.java.sip.communicator.impl.neomedia.codec.audio.opus.encoder.COMPLEXITY=10
> net.java.sip.communicator.packetlogging.PACKET_LOGGING_ENABLED=true
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647=acc1403273890647
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.ACCOUNT_UID=XXXXXXXX
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.PASSWORD=XXXXXXXXX
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.PROTOCOL_NAME=SIP
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.SERVER_ADDRESS=XXXXXXX
> 
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.SERVER_PORT=5061
> 
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.USER_ID=XXXXXXX
> 
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.SAVP_OPTION=1
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.PROXY_AUTO_CONFIG=true
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.DISPLAY_NAME=Jitsi Konferenz
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.DTMF_METHOD=RTP_DTMF
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.DTMF_MINIMAL_TONE_DURATION=70
> 
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.KEEP_ALIVE_INTERVAL=25
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.KEEP_ALIVE_METHOD=OPTIONS
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.VOICEMAIL_ENABLED=false
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.AMR-WB/16000=750
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.G722/8000=700
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.GSM/8000=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.H263-1998/90000=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.H264/90000=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.PCMA/8000=600
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.PCMU/8000=650
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.SILK/12000=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.SILK/16000=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.SILK/24000=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.SILK/8000=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.VP8/90000=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.iLBC/8000=10
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.opus/48000=1000
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.red/90000=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.speex/16000=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.speex/32000=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.speex/8000=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.telephone-event/8000=1
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.Encodings.ulpfec/90000=0
> 
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.OVERRIDE_ENCODINGS=false
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.DEFAULT_ENCRYPTION=true
> 
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.DEFAULT_SIPZRTP_ATTRIBUTE=true
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.ENCRYPTION_PROTOCOL.ZRTP=0
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.ENCRYPTION_PROTOCOL.SDES=1
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.ENCRYPTION_PROTOCOL.DTLS-SRTP=2
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.ENCRYPTION_PROTOCOL_STATUS.ZRTP=false
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.ENCRYPTION_PROTOCOL_STATUS.SDES=true
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.ENCRYPTION_PROTOCOL_STATUS.DTLS-SRTP=false
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.SDES_CIPHER_SUITES=AES_CM_128_HMAC_SHA1_80,AES_CM_128_HMAC_SHA1_32
> 
> 
> 
> net.java.sip.communicator.impl.protocol.sip.acc1403273890647.DOMAIN_BASE=XXXXXX
> 
> org.jitsi.jigasi.xmpp.acc.IS_SERVER_OVERRIDDEN=true
> org.jitsi.jigasi.xmpp.acc.SERVER_ADDRESS=127.0.0.1
> org.jitsi.jigasi.xmpp.acc.VIDEO_CALLING_DISABLED=true
> org.jitsi.jigasi.xmpp.acc.JINGLE_NODES_ENABLED=false
> org.jitsi.jigasi.xmpp.acc.AUTO_DISCOVER_STUN=false
> org.jitsi.jigasi.xmpp.acc.IM_DISABLED=true
> org.jitsi.jigasi.xmpp.acc.SERVER_STORED_INFO_DISABLED=true
> org.jitsi.jigasi.xmpp.acc.IS_FILE_TRANSFER_DISABLED=true
> net.java.sip.communicator.service.gui.ALWAYS_TRUST_MODE_ENABLED=true

# Environment details
---
Ubuntu 18.04
Jigasi 1.1-112-gb74b2e8-1
Jicofo 1.0-591-1
prosody 0.10.0-1build1

**Comment by netaskd** [comment]
I experiance the same bahavior when healthcheck is enabled via:
```
org.jitsi.jigasi.HEALTH_CHECK_SIP_URI=1234
```
and SDES is enabled via:
```
net.java.sip.communicator.impl.protocol.sip.acc1.SAVP_OPTION=1
net.java.sip.communicator.impl.protocol.sip.acc1.DEFAULT_ENCRYPTION=true
net.java.sip.communicator.impl.protocol.sip.acc1.DEFAULT_SIPZRTP_ATTRIBUTE=false
net.java.sip.communicator.impl.protocol.sip.acc1.ENCRYPTION_PROTOCOL.ZRTP=0
net.java.sip.communicator.impl.protocol.sip.acc1.ENCRYPTION_PROTOCOL.SDES=1
net.java.sip.communicator.impl.protocol.sip.acc1.ENCRYPTION_PROTOCOL.DTLS-SRTP=0
net.java.sip.communicator.impl.protocol.sip.acc1.ENCRYPTION_PROTOCOL_STATUS.ZRTP=false
net.java.sip.communicator.impl.protocol.sip.acc1.ENCRYPTION_PROTOCOL_STATUS.SDES=true
net.java.sip.communicator.impl.protocol.sip.acc1.ENCRYPTION_PROTOCOL_STATUS.DTLS-SRTP=false
net.java.sip.communicator.impl.protocol.sip.acc1.SDES_CIPHER_SUITES=AES_CM_128_HMAC_SHA1_80,AES_CM_128_HMAC_SHA1_32
```
@damencho could you please take a look on this? It started from commit: https://github.com/jitsi/jigasi/commit/641b2570a7d59a040e7b83fb85558b9fa92c6057
my logs here: https://pastebin.com/yD2U0S61

**Comment by damencho** [comment]
I think the problem is coming after merging https://github.com/jitsi/libjitsi/pull/528

**Comment by JonathanLennox** [comment]
Could you share the SDP that's triggering the error?

It sounds like libsrtp doesn't think the SRTP crypto salt is the right size for the selected crypto policy.  This might be an error in the SDP, or might be a bug in libjitsi.

**Comment by damencho** [comment]
Thanks @JonathanLennox 

@netaskd @KornKalle 
You can switch on packet logging if it is not on, and send us the pcap file from /var/log/jitsi/jigasi/....
You can send it to me damencho at jitsi dot org.

**Comment by JonathanLennox** [comment]
Inspecting the code, I think I found the issue: https://github.com/jitsi/libjitsi/pull/534 .  Are you able to build this and test?

**Comment by damencho** [comment]
And there will be a new build to test in unstable in a few minutes.

**Comment by netaskd** [comment]
Yeah, now it's working as expected in `jigasi: 1.1-122-g0bd6af9-1`
Thank you, guys!

**Comment by damencho** [comment]
Thanks for confirming @netaskd and thanks @JonathanLennox for the quick fix.
