### ISSUE TITLE
The latest commit is breaking calls

### ISSUE THREAD

**Issue by netaskd** [jitsi/jigasi#298]
## Description
Invite is not successful with Jigasi 1.1-123-g3883344-1 due to
```
An uncaught exception occurred in thread=Thread[Thread-74,5,main] and message was: org/jitsi/xmpp/extensions/jitsimeet/MediaPresenceExtension$Source
java.lang.NoClassDefFoundError: org/jitsi/xmpp/extensions/jitsimeet/MediaPresenceExtension$Source
```
Jigasi 1.1-122-g0bd6af9-1 works good.

## Current behavior
Log: https://pastebin.com/G8nGvhvS

**Comment by damencho** [comment]
MediaPresenceExtension That was removed from the code... Interesting seems it is still using old jitsi-desktop libraries

**Comment by damencho** [comment]
@netaskd Can you test 1.1-124 when it is out, should be in a few minutes.

**Comment by damencho** [comment]
jigasi_1.1-124-gd755b8d is out.

**Comment by netaskd** [comment]
@damencho Yeah, it works now. Thank you!

**Comment by damencho** [comment]
Nice. Yeah, it was my mistake, I forgot to update the desktop dependency which was the real fix for the transcribers ;)
