### ISSUE TITLE
Invite phone number - Failed to add participants

### ISSUE THREAD

**Issue by akam-it** [jitsi/jigasi#305]
Hello, I have just installed on debian 10 jitsi with jigasi.
I am trying to invite a phone number, but get error "Failed to add participants". I see error in console:
2020-08-03T12:00:18.540Z [features/invite] Error inviting phone number: 
<iq xmlns=​"jabber:​client" id=​"6e6cd3b6-c550-4b30-b48b-586c96afef31:​sendIQ" to=​"jtcsiv_coglxtst4@guest.meet.mydomain/​0CwHMFDC" type=​"error" from=​"cognitiveintegritiesdrawfurther@conference.meet.mydomain/​focus">​
<error type=​"cancel"><service-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error>​
</iq>​

2020-08-03T12:00:18.545Z [features/invite] 1 invites failed 

But when I am pressing button Invite I can see nothing in logs /var/log/{prosody,jisi}

A couple of days before I was able to invite a phone number to a conference, but then I had upgraded jitsi and reboot system and can't invite now. I am not sure the upgrade is the reason.

**Comment by Turbid** [comment]
try to restart jicofo and try again

https://community.jitsi.org/t/jigasi-failed-to-add-participants/46257/22

**Comment by akam-it** [comment]
it has been resolved by updating to the latest version.
