### ISSUE TITLE
Dial-in without lobby is broken

### ISSUE THREAD

**Issue by heikar** [jitsi/jigasi#320]
## Description
I have installed a test environment with the current nightly build of jitsi meet.
The configuration are the same as in my productive environment.
If someone call the dial-in number, then jigasi try to connect with the room e.g. 'roomname@lobby.domainname'.
This works if the lobby are activated but if the lobby is deactivated, the call is rejected.

## Current behavior
Rooms without lobby do not work.

**Comment by damencho** [comment]
Please use the community forum when you have questions or problems before opening new issues.

Try adding the following config:
`org.jitsi.jigasi.MUC_SERVICE_ADDRESS=conference.<<DOMAIN_BASE>>`

**Comment by heikar** [comment]
It works. Thank you
