### ISSUE TITLE
Transcription Not Working for Participants [Only host]

### ISSUE THREAD

**Issue by fremzy** [jitsi/jigasi#332]
## Description
Transcription does not work for the participants in a meeting. Only the host sees the captioning on screen. The "CC" button does not show up for other participants and neither does the captioning or the "TR" icon.

## Current behavior
Transcription button, icon and captions only show up on screen for meeting moderator

## Expected Behavior
Each meeting participant should be able to turn on transcription at will by clicking the "CC" button (which should be available for them]

## Possible Solution
Make "CC", "TR" and captions available to all meeting participants

## Steps to reproduce
1. Start a Jitsi meeting
2. Have other participants join the meeting
3. Click on the "CC" button to activate transcription

# Environment details
Ubuntu Server 20.04
Jitsi Meet 4857-1
Jigasi - Latest Unstable

**Comment by damencho** [comment]
This is fixed in the latest unstable versions of jitsi-meet.
https://github.com/jitsi/jitsi-meet/commit/20ce38bd4c48ce251804e5c4d69f225cf8fb50db
