### ISSUE TITLE
Invalid Origin SDP being Sent after Maven-ization

### ISSUE THREAD

**Issue by joshelson** [jitsi/jigasi#34]
I have seen a new issue attempting outbound calls from Meet after the latest upgrade.  We are now seeing the SDP o= header sent on invite as:

o=username-jitsi.org 0 0 IN null null

We would generally expect to see a session ID and IP information added to this.

**Comment by ltshark** [comment]
<dependency>
      <groupId>org.opentelecoms.sdp</groupId>
      <artifactId>java-sdp-nist-bridge</artifactId>
    </dependency>

to

<dependency>
      <groupId>org.opentelecoms.sdp</groupId>
      <artifactId>java-sdp-nist-bridge</artifactId>
      <version>1.2</version>
    </dependency>

**Comment by ltshark** [comment]
`<dependency>
      <groupId>org.opentelecoms.sdp</groupId>
      <artifactId>java-sdp-nist-bridge</artifactId>
    </dependency>`

to

`<dependency>
      <groupId>org.opentelecoms.sdp</groupId>
      <artifactId>java-sdp-nist-bridge</artifactId>
      <version>1.2</version>
    </dependency>`

**Comment by joshelson** [comment]
This in fact did resolve it.  Submitted [PR](https://github.com/jitsi/jigasi/pull/36) to merge.

**Comment by Toumassa** [comment]
Thanks @Itshark it resolved my problem too (calling issues with freeswitch).

**Comment by damencho** [comment]
This is now fixed. https://github.com/jitsi/jigasi/commit/0107a421f343931baa6d547494d9f2eb2c8298d9
