### ISSUE TITLE
Jigasi thread leak issue?

### ISSUE THREAD

**Issue by cyril-rm** [jitsi/jigasi#341]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
---

Jigasi seems to suffer from a "thread leak" upon handling hundreds of SIP calls, where the number of open threads increase and seems to never decrease.

I ran 10 tests, each tests consists of 80 sip calls per instance.
Each sip call = 1 conference room with 1 user (so 2 users in the same conference room since 2 instances have 80 sip calls each).
Here are the number of threads (using /about/stats route) that I got after each run:

“threads”:718.
“threads”:2231
“threads”:2380
“threads”:2929
“threads”:3615
“threads”:4049
“threads”:4499
“threads”:5047
“threads”:6010
“threads”:7054

## Current behavior
---

Number of threads increasing after each call

## Expected Behavior
---

Threads to properly decrease when calls are finished

## Possible Solution
---

unknown

## Steps to reproduce
---

Handle hundred of calls using the same jigasi on the same host, check open threads after a while, repeat tests to confirm that the number of threads is increasing more than it decreases even when there are no more active calls.

# Environment details
---

2x C5.Xlarge EC2 instances
1 ECS instance = 1 Jigasi + 1 Asterisk on the same host, docker deployment (network mode=host), jigasi connecting to sip:localhost.
Tested releases: 
- https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-5142
- https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-5390-3
Same behavior on the two instances.

**Comment by damencho** [comment]
What is the jigasi version you used?

**Comment by cyril-rm** [comment]
I'm running Jigasi 1.1.166-g929a439

**Comment by damencho** [comment]
I will be looking at this in the following days. Hopefully, I will have a new version to test. Thank you.

**Comment by damencho** [comment]
@cyril-rm when you are testing are you making dial-out from jigasi or all calls are dial-in?

**Comment by cyril-rm** [comment]
I'm making only dial-in calls.
Asterisk receive the calls, set the X-room-name header from 0 to N, and pass the call to jigasi.

**Comment by damencho** [comment]
Do you have the healthchecks running? 

org.jitsi.jigasi.HEALTH_CHECK_INTERVAL=20000
org.jitsi.jigasi.HEALTH_CHECK_SIP_URI=healthcheck

**Comment by damencho** [comment]
Nope, it doesn't matter actually.

**Comment by damencho** [comment]
Do you have org.jitsi.jigasi.JVB_INVITE_TIMEOUT in the config and what is its value?

**Comment by damencho** [comment]
I cannot reproduce this. Which prosody version do you use? We have seen similar behavior when prosody-0.10 is used there ... 
You can do the test where you see a lot of threads, wait few minutes if any call is about to expire(by default 30 seconds if JVB_INVITE_TIMEOUT is not set) to give it time and execute `/usr/share/jigasi/collect-dump-logs.sh` and send me the dump privately damencho at jitsi dot org. And I can take a look when time permits.

**Comment by cyril-rm** [comment]
Hi,

Here are my prosody informations:

> Prosody 0.11.8
> 
> # Prosody directories
> Data directory:     /config/data
> Config directory:   /config
> Source directory:   /usr/lib/prosody
> Plugin directories:
>   /prosody-plugins/
>   /prosody-plugins-custom
>   /usr/lib/prosody/modules/
> 
> 
> # Lua environment
> Lua version:                    Lua 5.2
> 
> Lua module search paths:
>   /usr/lib/prosody/?.lua
>   /usr/local/share/lua/5.2/?.lua
>   /usr/local/share/lua/5.2/?/init.lua
>   /usr/local/lib/lua/5.2/?.lua
>   /usr/local/lib/lua/5.2/?/init.lua
>   /usr/share/lua/5.2/?.lua
>   /usr/share/lua/5.2/?/init.lua
> 
> Lua C module search paths:
>   /usr/lib/prosody/?.so
>   /usr/local/lib/lua/5.2/?.so
>   /usr/lib/x86_64-linux-gnu/lua/5.2/?.so
>   /usr/lib/lua/5.2/?.so
>   /usr/local/lib/lua/5.2/loadall.so
> 
> LuaRocks:               Not installed
> 
> # Network
> 
> Backend: epoll
> 
> # Lua module versions
> lfs:            LuaFileSystem 1.6.3
> lxp:            LuaExpat 1.3.0
> socket:         LuaSocket 3.0-rc1
> ssl:            0.7.1

I checked for JVB_INVITE_TIMEOUT in my JVB configuration files and has not found any occurences inside jvb.conf, I checked sip-communicator.properties and there are only one line inside (net.java.sip.communicator.packetlogging.PACKET_LOGGING_ENABLED=false), everything else is inside jvb.conf.

I don't know where to check for JVB version (I used the docker images from this release: https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-5390-3 for my ECS deployment)

As for the dump, the script was not working, jmap&jstack are not available on the jdk release used for the docker images:

```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)
```

I have no idea on how to install them to provide you the dump

**Comment by cyril-rm** [comment]
Hello,

Do you have any feedback regarding this issue?
Is there something that I can do/provide to help to identify the issue?

**Comment by damencho** [comment]
Thanks to @cyril-rm for testing with his help and some dumps from the jigasis we run, we managed to pin several issues and fix them. And latest tests show good improvement.

https://github.com/jitsi/jigasi/commit/e1aef85f7ab6aa0567e9db4ef353cc81b950cd78
https://github.com/jitsi/jigasi/commit/d1a2e18b6cdc12e63ac923130a2d84ea5d3b7676
https://github.com/jitsi/jigasi/commit/069a50b138bf743cae74a105b78e90cd96f4cbf1
https://github.com/jitsi/jigasi/pull/355

Thanks for the help

**Comment by damencho** [comment]
@saghul I think we should by default install on jicofo, jvb and jigasi image in docker the jdk not only jre, so we can use the collect dump scripts, as those are useful in situations like this, where we need som logs and input for a problem.

**Comment by saghul** [comment]
We can look into that.
