### ISSUE TITLE
Changing user agent

### ISSUE THREAD

**Issue by Neurosis404** [jitsi/jigasi#369]
Hi, 

I'm having a simple question, not a bug. I need to change the user-agent for the SIP registration. We are using Innovaphone and there is a feature that automatically adds the conference room header, as long as the user agent contains the word "jitsi". The current user agent is "Jigasi1.1.195-g65ef768Linux". 

Is there a way to change the user agent?

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

There is no easy way without recompiling/rebuilding jigasi.
An easy workaround would be in /etc/jitsi/jigasi/config try adding in JAVA_SYS_PROPS the following `-Dos.name='Ubuntu-jitsi'`, I hope that works.

**Comment by maITbig** [comment]
Hi,

I have the same problem with Jigasi + innovaphone on Kubernetes. But the workaround didn't work, when I edit the the /etc/jitsi/jigasi/config file in the image with sed. Have you any idea?

I use the version = stable-7648-4
