### ISSUE TITLE
Integrate SIP Video

### ISSUE THREAD

**Issue by sunshuvo** [jitsi/jigasi#39]
Is it possible to SIP video call from jitsi meet? I get only audio. But, the video is badly needed to me. Is not is supported? Or are there something to configured?

**Comment by aamoyg** [comment]
+1 this would be extremely useful

**Comment by emcho** [comment]
We are likely adding SIP videi calling to the jibri project. Jigasi will remain audio only.

**Comment by fuqiangleon** [comment]
@emcho hi,sir ,how can add SIP video to conference with jibri ?could you give us some help ?
