### ISSUE TITLE
SIP call cannot be completed. an 400 error returned.

### ISSUE THREAD

**Issue by dnoviko** [jitsi/jigasi#42]
using jigasi_1.0-107_amd64.deb

176.99.xx.xxx - jigasi
54.200.xx.xxx kamailio sip proxy

kamailio relaying call to freeswitch and fs returning **SIP/2.0 400 Bad Session Description**

sip header from jigasi is mailformed, log from kamailio:

> Nov 28 11:47:18 kamailio /usr/sbin/kamailio[363871]: ERROR: <core> [parser/sdp/sdp_helpr_funcs.c:468]: extract_mediaip(): no `IP[4|6]' in `o=' field
> Nov 28 11:47:18 kamailio /usr/sbin/kamailio[363871]: ERROR: <core> [parser/sdp/sdp.c:416]: parse_sdp_session(): can't extract origin media IP from the message

the o: header not included ip information.

sip trace:
    

> 176.99.xx.xx.5060 > 54.200.xx.xxx.5060: [bad udp cksum 0x1ca5 -> 0x95e1!] SIP, length: 1193
>         INVITE sip:10005@54.200.xx.xxx SIP/2.0
>         Call-ID: 3c894dd67604449ea7a5ffb965c86713@0:0:0:0:0:0:0:0
>         CSeq: 2 INVITE
>         From: "120" <sip:120@54.200.xx.xxx>;tag=513003ea
>         To: <sip:10005@54.200.xx.xxx>
>         Max-Forwards: 70
>         Contact: "120" <sip:120@176.99.xx.xxx:5060;transport=udp;registering_acc=54_200_xx_xxx>
>         User-Agent: Jitsi2.9.0.build.by.SVNLinux
>         Content-Type: application/sdp
>         Jitsi-Conference-Room: hardantelopesconjureamazingly
>         Via: SIP/2.0/UDP 176.99.xx.xxx:5060;branch=z9hG4bK-333335-46fbbb746dff202c9ee69bfbd8a7be6a
>         Proxy-Authorization: Digest username="120",realm="54.200.xx.xxx",nonce="WDwaclg8GUZZ/g391A/fKCqLOwbZMrS0",uri="sip:10005@54.200.xx.xxx",response="7ee349b5377d4fe042d3c2fbb17fb740"
>         Content-Length: 463
> 
>         v=0
>         o=120-jitsi.org 0 0 IN null null
>         s=-
>         c=IN IP4 176.99.xx.xxx
>         t=0 0
>         m=audio 10039 RTP/AVP 96 97 9 0 8 98 101
>         a=rtpmap:96 opus/48000/2
>         a=fmtp:96 usedtx=1
>         a=ptime:96 20
>         a=rtpmap:97 AMR-WB/16000
>         a=rtpmap:9 G722/8000
>         a=rtpmap:0 PCMU/8000
>         a=rtpmap:8 PCMA/8000
>         a=rtpmap:98 iLBC/8000
>         a=rtpmap:101 telephone-event/8000
>         a=extmap:1 urn:ietf:params:rtp-hdrext:csrc-audio-level
>         a=extmap:2 urn:ietf:params:rtp-hdrext:ssrc-audio-level
>         a=rtcp-xr:voip-metrics
> 
> 11:47:44.222519 IP (tos 0x0, ttl 35, id 28252, offset 0, flags [none], proto UDP (17), length 402)
>     54.200.xx.xxx.5060 > 176.99.xx.xxx.5060: [udp sum ok] SIP, length: 374
>         SIP/2.0 100 trying -- your call is important to us
>         Call-ID: 3c894dd67604449ea7a5ffb965c86713@0:0:0:0:0:0:0:0
>         CSeq: 2 INVITE
>         From: "120" <sip:120@54.200.xx.xxx>;tag=513003ea
>         To: <sip:10005@54.200.xx.xxx>
>         Via: SIP/2.0/UDP 176.99.xx.xxx:5060;branch=z9hG4bK-333335-46fbbb746dff202c9ee69bfbd8a7be6a;rport=5060
>         Server: kamailio (4.4.2 (x86_64/linux))
>         Content-Length: 0
> 
> 11:47:44.223755 IP (tos 0x0, ttl 35, id 28253, offset 0, flags [none], proto UDP (17), length 501)
>     54.200.xx.xxx.5060 > 176.99.xx.xxx.5060: [udp sum ok] SIP, length: 473
>         SIP/2.0 400 Bad Session Description
>         v:SIP/2.0/UDP 176.99.xx.xxx:5060;rport=5060;branch=z9hG4bK-333335-46fbbb746dff202c9ee69bfbd8a7be6a
>         f:"120"<sip:120@54.200.xx.xxx>;tag=513003ea
>         t:<sip:10005@54.200.xx.xxx>;tag=vgaNvjgB225jD
>         i:3c894dd67604449ea7a5ffb965c86713@0:0:0:0:0:0:0:0
>         CSeq:2 INVITE
>         User-Agent:
>         Accept:application/sdp
>         Allow:INVITE,ACK,BYE,CANCEL,OPTIONS,MESSAGE,INFO,UPDATE,REGISTER,REFER,NOTIFY
>         k:timer,path,replaces
>         u:talk,hold,conference,refer
>         l:0
>

**Comment by damencho** [comment]
Please, use the mailinglist for questions and problems, before opening issues.
Did you try version 108? java-sdp-nist-bridge was updated in that version, which I think is fixing the problem.
