### ISSUE TITLE
JiGASi concurrent calls

### ISSUE THREAD

**Issue by oerodriguezn** [jitsi/jigasi#439]
Hi. 
I would like to know if there is any documentation about how many instances of JIGASi do I need to have multiple concurrent calls? Is it like JVB or like JIBRI that needs a instace per room ? 

If it is like JVB. How many calls supports one instance ? Is there any special configuration when having JITSI with multiple JVB ?

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

It is like ivb. And there is no number to mention. This depends on the host its running and the configuration it is running with.

Jigasi can be run to mix the audio to the sip side or it can be just routing packets and leave the sip side to do the mixing. The later one is more performant and with that you can run by a lot of calls, like hundred and more on a single instance. There is a stress value reported in the stats to look out for doing auto scaling

**Comment by oerodriguezn** [comment]
Thanks @damencho , do you have any documentation of JIGASE configured on mode just routing?
