### ISSUE TITLE
Impossible to make jigasi work with tokens

### ISSUE THREAD

**Issue by sc-sycer** [jitsi/jigasi#446]
Since last major update with jigasi, can't make outgoing calls because it always returns token mismatched

jwt works well for normal participants, but jigasi doesn't. It connects well to prosody via auth, but when trying to make a call from the invite dialog, after introducing the number it stops and the log says:

2022-09-24 21:06:55.443 GRAVE: [72] net.java.sip.communicator.impl.protocol.jabber.ChatRoomJabberImpl.joinAs: Failed to join room <roomname>@conference.<host> with nickname: <nickname>
org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from <roomname>@conference.<host>/<nickname>: XMPPError: not-allowed - cancel [Room and token mismatched]

This was working flawlessly before. Something changed with the latest changes introduced that added the new virtualhost jigasi.meet.jitsi at the end, which takes some tokens from an asap_key_server that I'm not sure what they're for. Even removing all the virtualhost declaration the system does the same. jigasi@<host> is added to the conference admin list.

The only way I have to make jigasi accept making calls is to set the main virtual host authentication to anonymous.

Any idea about how to solve it? Thank you!

**Comment by damencho** [comment]
Set **`enable_domain_verification = false`** under your main virtual host.

The default switched from false to true and may cause problems with jigasi and jibri in some cases.

**Comment by sc-sycer** [comment]
@damencho , you're a God. Worked perfectly. Thank you very much for all the work and for the speed to respond!!

For the record, jibri didn't seem to complain!
