### ISSUE TITLE
 Why is jigasi transcription subtitle only showing in moderator

### ISSUE THREAD

**Issue by ChGunay** [jitsi/jigasi#461]
## Description
---Hello, I activated the transcript with google speech to text on jitsi. But the transcript subtitle is only displayed on the screen of the room owner logged in with the jwt token. I want it to show on guest screens as well. How can I do this?

## img
moderator uı
<img width="260" alt="Ekran Resmi 2022-11-04 18 11 11" src="https://user-images.githubusercontent.com/41910291/200017417-a573828a-a3eb-4b39-9359-7dc5cf68ab48.png">
.env file
<img width="498" alt="Ekran Resmi 2022-11-04 18 11 37" src="https://user-images.githubusercontent.com/41910291/200017418-9ea55c41-3cca-4d71-9be9-913c58f63dcc.png">
guest uı
<img width="253" alt="Ekran Resmi 2022-11-04 18 10 57" src="https://user-images.githubusercontent.com/41910291/200017406-b21f77e2-eb5b-4834-b595-daacf353cd43.png">

It is only visible to the owner of the room logged in with the jwt toke. Unfortunately, this button does not appear for guest users who are not logged in.
---

# Environment details
my jitsi version: docker-jitsi-meet-stable-7648-4

---

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

This issue has nothing to do with jigasi and please stick to the open discussion and do not open multiple threads about it.
