### ISSUE TITLE
VOSK - wrong coding in file

### ISSUE THREAD

**Issue by SkyTaurus** [jitsi/jigasi#483]
If I set 
org.jitsi.jigasi.transcription.SAVE_TXT=true
 I got a  file in tmp folder but russian letters as question marks.
I looked with the HEX  editor - the same code 3F for all russian words
File has ASCII coding

Need save file to UTF-8 format

@nshmyrev please take a look

**Comment by damencho** [comment]
I believe this is fixed https://github.com/jitsi/jigasi/commit/39cf66a7197a19d1b6259b5dfdb4557a5d180f7d
