### ISSUE TITLE
Getting Transcription in the form of JSON object

### ISSUE THREAD

**Issue by sanhitapatil** [jitsi/jigasi#492]
I am receiving transcription data in the form of JSON objects like this 
Sanhita:"{“partial” : “”,text:“”}"
Sanhita:"{“partial” : “”,text:“”}"
Sanhita:"{“partial” : “”,text:“”}"
![Screenshot from 2023-08-17 17-33-48](https://github.com/jitsi/jigasi/assets/62783922/f0482dfe-1876-43d8-a98f-9a24efc2704d)

could you tell me where I am going wrong and why it is showing like this ?

**Comment by damencho** [comment]
@charles-zablit @88fingerslukee @nshmyrev any idea? Do you reproduce this?

**Comment by charles-zablit** [comment]
Yes, this was reported [on the forums](https://community.jitsi.org/t/jigasi-randomly-starts-sending-raw-vosk-json-response-as-subtitles/117831).
There was an attempt at fixing the issue in [this PR](https://github.com/jitsi/jigasi/pull/451).

**Comment by sanhitapatil** [comment]
How can I implement it when I am working on jigasi and jitsi-meet packages ?

**Comment by charles-zablit** [comment]
I don't think you have another choice but to build from source.

**Comment by charles-zablit** [comment]
> Could you share any tutorial or steps to integrate jitsi-meet and jigasi ?

I don't have any sorry, when I was trying to set it up, we used the docker images and made the changes we needed to make it work.
