### ISSUE TITLE
Captions Button and Transcripts Visible to Moderator Only

### ISSUE THREAD

**Issue by bharath-naik** [jitsi/jigasi#494]
## Description
The captions button and the resulting transcripts are currently only visible and accessible to the meeting's moderator. This significantly limits the accessibility and usefulness of the feature.

## Current behavior
Only the moderator can see the captions button and enable it. Consequently, only the moderator can view the resulting transcripts/captions during the meeting.

## Expected Behavior
The captions button and the resulting transcripts/captions should be visible and accessible to all meeting participants. Anyone should be able to enable or disable this feature according to their needs.

## Possible Solution
Modify the permissions or settings related to the captions feature to make it publicly available for all participants, not just the moderator.

## Steps to reproduce
Start a Jitsi meeting with one moderator and at least one additional participant.
Observe that only the moderator has access to the captions button.
Enable captions as the moderator.
Observe that only the moderator can see the resulting transcripts/captions.

# Environment details
Jigasi version: used stable-8252 tag in Dockerfile
Operating System: [e.g., Ubuntu 20.04]
Browser details : [Chrome, microsoft edge and Firefox]

**Comment by damencho** [comment]
We don't have plans of changing this. 
This feature requires server side resources and is expensive we cannot allow any anonymous participant to turn this on, so this is left only for those that are moderator which are authenticated.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by bmilde** [comment]
> This significantly limits the accessibility and usefulness of the feature.

I have to agree with @bharath-naik here. It would be nice if this was configurable. For some people it requires too much server side resources, but for plenty of people it doesn't. Also if I'm the moderator I'd expect to be able to turn CCs for the entire meeting, i.e. everybody sees the same subtitles if the moderator enables them. It would be nice if this was configurable as well. Currently anonymous users can't enable CCs and the moderator can't set CCs for them. 

Also documentation is currently lacking - who can see CCs, who can enable CCs etc.

**Comment by damencho** [comment]
> Currently anonymous users can't enable CCs and the moderator can't set CCs for them

Moderator can turn them on and after that any guest can enable them.



> Also if I'm the moderator I'd expect to be able to turn CCs for the entire meeting

This had been already added 
https://github.com/jitsi/jitsi-meet/blob/0149b5f6e6438dc9e57f0fd980ea818a3c7e219e/config.js#L486

**Comment by bmilde** [comment]
> Moderator can turn them on and after that any guest can enable them.

Will do some more testing tomorrow, but I remember that this didn't work with my installation. Maybe a config issue on my end.

> https://github.com/jitsi/jitsi-meet/blob/0149b5f6e6438dc9e57f0fd980ea818a3c7e219e/config.js#L486

Very cool, thank you for the hint! :)
