### ISSUE TITLE
Call without area code to SIP number

### ISSUE THREAD

**Issue by sluka82** [jitsi/jigasi#50]
Hello.
I've installed jitsi meet and jigasi.
Everything works perfect. Jitsi Meet accept incoming sip call.
But when I try to call to sip number from Jitsi Meet the US area code is inserted before the number.
I need to call to local sip number, the same server jigasy registered, so I don't need any area codes inserted before.
Is it possible to fix the config of Jitsi Meet or Jigasy, or I need to fix the dialplan rules in my PBX.
My PBX is Elastix.

Thank you.

**Comment by damencho** [comment]
Hi this is known issue in jitsi-meet. 
There is a new option to download a predefined list of areacodes. This is by default disabled and should not show anything. The current workaround is just to enable it. Soon we will fix it and will push a new stable version.
http://lists.jitsi.org/pipermail/users/2017-June/013147.html

**Comment by rasos** [comment]
Works nice, some flags are missing, though (e.g. Austria).

**Comment by damencho** [comment]
This had been fixed in latest nightlies, and you can now disable the codes and it will work as before.

**Comment by globalcorpp** [comment]
@rasos can you tell me what flag missing?
