### ISSUE TITLE
SIP video

### ISSUE THREAD

**Issue by billsimon** [jitsi/jigasi#51]
jigasi does not appear to relay any video streams to video-capable SIP clients. I enabled H264 in jigasi's sip-communicator.properties and see that the codec is negotiated and accepted, but no video is relayed.

**Comment by damencho** [comment]
Yep, jigasi supports only audio.
If you want video capable sip connection you need to check https://github.com/jitsi/jibri
There is an option for a sip video connection, but the project is in early stage and missing some documentation.

**Comment by ashward** [comment]
Hmm - seems strange that this has been closed. Does that mean there's no intention at all to support SIP video through jigasi?

**Comment by damencho** [comment]
Yes, it is audio only. There are no plans for changing this.

**Comment by ashward** [comment]
Just out of interest, is the main issue the video transcoding (between VP8 and H.264)? If, in a controlled environment, meet was forced to only use H.264 (as per https://github.com/jitsi/jitsi-meet/issues/877) then would this make things work? I can't see anything in the source code which would stop it working if all the codecs match up.

**Comment by damencho** [comment]
In theory, it should work. Not sure about the error corrections and stuff like that, this will affect the quality a lot and needs tweaking and not a trivial work to make it work correctly.
Yep, the initial statement was because of the transcoding, but you are right currently browsers support h264.

**Comment by damencho** [comment]
As I said this is not on our roadmap currently, so any contributions are welcome.

**Comment by damencho** [comment]
About the translator approach it will work only one way, from sip to the conference. From the conference to sip you need encoding and transcoding, you need to implement MCU :) which is not a trivial task.

**Comment by fuqiangleon** [comment]
@damencho hello sir,  we have been  finding a solution to  got video from SIP server ,is there  any roadmap to support it now ?

If not  ,could you give us some points or maybe we can develop it  and contribute it back .

Thank you very much.

**Comment by damencho** [comment]
@fuqiangleon The only way to add a sip video-capable device is to use jibri: https://github.com/jitsi/jibri/blob/master/doc/sip_gateway.md

**Comment by billsimon** [comment]
@damencho could you explain this? Are you talking about two-way SIP video with multiplexing? Isn't Jibri for recording/streaming?

**Comment by damencho** [comment]
@billsimon, yes, jibri is for recording and streaming, but we also use the same technology to receive/send video and audio from/to a legacy sip endpoint. This way the endpoint will see the whole user experience for a normal web client in just one video stream (the same thing you will see in streaming or recording, but this time it is realtime).
Our main test scenario was with some LifeSize room equipment.

**Comment by billsimon** [comment]
Does it work the same as the readme describes, using the virtual framebuffer and thus limited to one SIP session per Jibri VM? 

    It works by launching a Chrome instance rendered in a virtual framebuffer and capturing and encoding the output with ffmpeg. It is intended to be run on a separate machine (or a VM), with no other applications using the display or audio devices. Only one recording at a time is supported on a single jibri.

**Comment by sliderxtm** [comment]
any update for sip video support. The Jibri still only way today?

**Comment by damencho** [comment]
Yes, and that will not change.

**Comment by sliderxtm** [comment]
Does jibri transcoding video flow from vp8, that came from ordinary clients to what need for sip endpoint on other side (h264 for example) ?

**Comment by damencho** [comment]
Yep.
