### ISSUE TITLE
Where can I find the dependency source code? (jitsi-protocol*)

### ISSUE THREAD

**Issue by kixiro** [jitsi/jigasi#536]
Hi

where can I find the dependency source code?

I see dependencies in the project, but I can't find the source codes for these dependencies

https://github.com/jitsi/jitsi-maven-repository/tree/master/snapshots/org/jitsi/jitsi-protocol
https://github.com/jitsi/jitsi-maven-repository/tree/master/snapshots/org/jitsi/jitsi-protocol-jabber
https://github.com/jitsi/jitsi-maven-repository/tree/master/snapshots/org/jitsi/jitsi-protocol-media
https://github.com/jitsi/jitsi-maven-repository/tree/master/snapshots/org/jitsi/jitsi-protocol-sip

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by damencho** [comment]
It is https://github.com/jitsi/jitsi

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi/tree/master/modules/impl/protocol-jabber
https://github.com/jitsi/jitsi/tree/master/modules/service/protocol
https://github.com/jitsi/jitsi/tree/master/modules/service/protocol-media
https://github.com/jitsi/jitsi/tree/master/modules/impl/protocol-sip
