### ISSUE TITLE
Jigasi No JVB room name provided in INVITE header

### ISSUE THREAD

**Issue by gitwittidbit** [jitsi/jigasi#562]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Trying to ingrate jitsi (running in docker) with my sip server via jigasi. Jigasi successfully registers with the server and also gets notified of an incoming call but it declines because no room name is provided in the sip INVITE header. I cannot configure my server to include this header, so I tried to provide a DEFAULT_JVB_ROOM_NAME in the docker .env file. But this does not work. I also tried to put org.jitsi.jigasi.DEFAULT_JVB_ROOM_NAME directly in the sipcommunciator.properties file but this also does not work and it also seems to get removed when the jigasi container is recreated. I also tried to just use the siptest room but that also does not work.

## Current behavior
Jigasi declines incoming sip calls because no room name is provided in the INVITE header and because it does not fall back to the configured default room or to the (unconfigured) siptest room.

## Expected Behavior
Jigasi honors the configured default room and does not decline the incoming sip invite

## Possible Solution
No idea

## Steps to reproduce
Set up jitsi including jigasi via docker as per official docs. 
Provide jigasi name and password for sip server.
Call jigasi internally
Observe logs

# Environment details
DEFAULT_JVB_ROOM_NAME=dialin@meet.example.com

**Comment by damencho** [comment]
For docker this is
```
org.jitsi.jigasi.DEFAULT_JVB_ROOM_NAME=siptest@muc.meet.jitsi
```
And you need to add it in a custom file 
/config/custom-sip-communicator.properties

https://github.com/jitsi/docker-jitsi-meet/blob/74d913f58acfe01573aa335ea363b8487137078d/jigasi/rootfs/etc/cont-init.d/10-config#L95

**Comment by damencho** [comment]
In docker env you need to set
JIGASI_SIP_DEFAULT_ROOM

https://github.com/jitsi/docker-jitsi-meet/blob/74d913f58acfe01573aa335ea363b8487137078d/jigasi/rootfs/defaults/sip-communicator.properties#L47C12-L47C35

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.
