### ISSUE TITLE
Jigasi support video in conference?

### ISSUE THREAD

**Issue by elendil1979** [jitsi/jigasi#58]
Hello,

i have a jigasi registered in a Cisco VCS and i have call between my B2B domain and a jitsi room, but this connection is only for audio, can i have video too?

Always appears a message over the avatar:

Video has been turned off to save bandwidth. Can i enable video?

**Comment by saghul** [comment]
Hi there,

Jigasi doesn't currently support video. For video room support take a look at Jibri. Note that the documentation is scarce at the moment.

Cheers,
