### ISSUE TITLE
SIP account issue.

### ISSUE THREAD

**Issue by SheriefAlaa** [jitsi/jigasi#81]
Hello,

I am trying to replicate jitsi's demo at app.boardhub.io and things are going smooth except for jigasi. I pretty much followed package installation and provided it with the input it needed (as far as I understand) but whenever someone calls the meeting ID he receives 'unsupported domain'.

Any help would be appreciated.

Thanks.

**Comment by aaronkvanmeerten** [comment]
Hi there,

The reason this is failing for you is that you’re using the meet.jit.si <http://meet.jit.si/> conference mapper API directly.  This is a cloud service intended only to service the meet.jit.si <http://meet.jit.si/> service, and not intended to integrate against for 3rd party installations.   Instead, you’ll need to create yourself this service if you wish to have dial in/out support.  The conference mapper API swagger is published in the jitsi meet project, and you’ll need to implement a service which provides the same functionality, including phone numbers mapped to a pool of Jigasi instances and an IVR system which can map from conference ID back to the conference JID.

Sorry to say, this is not a trivial amount of work to build or maintain.  My suggestion is to take it one step at a time, first by connecting in a single jigasi instance, then beginning to build the conference mapper services and IVR once you see a basic jigasi functioning against your instance.

Cheers,

-Aaron

**Comment by aaronkvanmeerten** [comment]
After discussing with the team, I want to clarify something.  It’s fine to continue to use the conferenceMapper service to map your conferences to specific IDs.  However, you will still need to implement your own IVR system, your own pool of Jigasi instances, and the phone numbers mapped to them.  Then you’d implement your own implementation for phoneNumberList which would provide the jitsi meet client the phone numbers associated with your own phone in system.

Cheers,

-Aaron

**Comment by SheriefAlaa** [comment]
Hi @aaronkvanmeerten,

Thanks for the clarification.

**Comment by VectorformIT** [comment]
@SheriefAlaa :
I know this is from last year but since others might be wondering, I did get this working in conjunction with FreePBX, an Asterisk Dialplan, and a little bit of easy bash scripting and PHP/JSON.
The PHP just serves a static JSON object that emulates the phoneNumberList, and as @aaronkvanmeerten suggested I just use their conferencemapper service api. There are options in the jitsi meet configuration file to point at these two things.
I intend to document it all later but its working wonderfully.

**Comment by VectorformIT** [comment]
This is how I got it working in detail.
This is assuming you're going to use a FreePBX Asterisk server and Active Directory for LDAP
https://evilcreamsicle.com/index.php/2018/03/28/jitsi-meet-w-call-in-and-active-directory/

**Comment by damencho** [comment]
Thanks for sharing with the community.

**Comment by cbeckr** [comment]
@VectorformIT Thanks for posting, it seems your site is down at the moment. Are you able to share this somewhere else?

**Comment by RuiPereira** [comment]
> @VectorformIT Thanks for posting, it seems your site is down at the moment. Are you able to share this somewhere else?

@VectorformIT +1 I would also be interested on this info, is it available somewhere else?

**Comment by VectorformIT** [comment]
Yeah... Site is down sorry. I'll try and get that posted elsewhere

**Comment by EvilCreamsicle** [comment]
@cbeckr @RuiPereira It should be back up now, let me know if you have access issues.

**Comment by RuiPereira** [comment]
@EvilCreamsicle It works, thanks!

**Comment by fernand0abreu** [comment]
@EvilCreamsicle, your site is down... :/
Can you send me a copy of your tutorial?
https://evilcreamsicle.com/index.php/2018/03/28/jitsi-meet-w-call-in-and-active-directory/

**Comment by RuiPereira** [comment]
@fernand0abreu I managed to grab a screenshot of @EvilCreamsicle site last time it was online. Here it is:
[Jitsi Meet _w Call-In and Active Directory – EvilCreamsicle.com.pdf](https://github.com/jitsi/jigasi/files/3901605/Jitsi.Meet._w.Call-In.and.Active.Directory.EvilCreamsicle.com.pdf)

**Comment by fernand0abreu** [comment]
@RuiPereira Thank you :)

**Comment by EvilCreamsicle** [comment]
@fernand0abreu @RuiPereira 
Sorry guys, it's hosted out of a location with a dynamic IP, and apparently my dynamic DNS client has failed to function correctly.
I'll get it back online tonight once I get out of work. (its 11:30AM here, so... should be up in 8 hours or so)
