### ISSUE TITLE
Problems registering Jigasi with FreeSWITCH

### ISSUE THREAD

**Issue by jonaslindblom** [jitsi/jigasi#95]
I am having some problems (SIP-) registering Jigasi with FreeSWITCH. The setup is as follows:

* A FreeSWITCH instance configured in AWS, other SIP clients can connect and use without problems.
* A vanilla Jitsi system installed locally (with self signed certs), setup according to the quick installer. Seems to work fine in other aspects.

Attaching the Jigasi sip-communicator.properties, the Jigasi.log and the SIP trace from FreeSWITCH. To me it seems like Jigasi does not try to authenticate when challenged?

I saw in the mailing lists that it was suggested to use Jitsi Desktop to connect to the SIP-server first and then copy the sip-communicator.properties from there.

* It works fine to connect to the FreeSWITCH using the latest stable Jitsi Desktop for Mac, but the sip-communicator file (located in "~/Library/Application Support/Jitsi") is empty ...

* Doing the same thing from the latest stable Jitsi Desktop for Ubuntu or Windows, I have the same issue as with Jigasi reported here.

Logs and configuration files in this zip: [logsandconfig.zip](https://github.com/jitsi/jigasi/files/1832879/logsandconfig.zip)

**Comment by damencho** [comment]
So the problem is "A timeout occurred while trying to connect to the server."
Apparently your config for the sip account is not correct. The easiest way is as you have seen configure it through Jitsi Desktop and use those settings. 
Currently Jitsi Desktop by default uses local database to store config, to force it using properties file, go to the home folder where you will have an empty sip-communicator.properties delete everything there (loosing your current Jitsi Desktop configuration) and create an empty file names ".usepropfileconfig" and start the application again.
Now it will use the properties file and once you configure correctly your FreeSwitch sip account you can use its settings inside jigasi.

**Comment by jonaslindblom** [comment]
Thanks, I can now get Jitsi Desktop for Mac to produce and use the sip-communicator.properties file using the method you described. The result seems however to be the same: Jigasi keeps retrying sending SIP REGISTER to FreeSWITCH without adding Authorization: until it times out. I tried both including just the parts of the generated sip-communicator that seemed relevant and also using it untouched with Jigasi.

Jitsi Desktop for Mac on the other hand, does only one SIP REGISTER without Authorization: , after that it adds it, and is able to connect. Attaching such a successful SIP trace also for comaprison here: 
[freeswitch.siptrace.successful.log](https://github.com/jitsi/jigasi/files/1835084/freeswitch.siptrace.successful.log)

**Comment by damencho** [comment]
Yep, this is how it works. Sends a register without Authorization, gets an auth required with a challenge and then adds the authorization.
I suspect for some reason that the REGISTER from Linux does not hit your server. Check the address it goes to and make sure the settings about server address and proxy are the same.

**Comment by jonaslindblom** [comment]
Thanks, but not quite sure I get what you mean ... with Jigasi I have Linux on both ends :) . And the SIP register requests from Jigasi (Jigasi on my local Ubuntu box sends multiple, I included only the first in the log) for sure reaches the FreeSWITCH Debian box  (the SIP trace is from that side). But it seems that Jigasi never adds the Authorization ...

Or, hmmm,  is your theory that it is the Unauthorized responses that never get back to Jigasi? Would be a little strange since Jitsi desktop seem able to deal with it (behind the same NAT)?

**Comment by jonaslindblom** [comment]
Note that there are now two SIP traces from the FreeSWITCH side (one where it works, from Jitsi Desktop, and one with missing Auth from Jigasi) attached here.

Can I maybe get Jigasi to do similar logging to be able to tell what it sees?

**Comment by damencho** [comment]
Hum, if you are seeing that the register goes to FreeSWITCH I would suspect that the response doesn't reach back to jigasi.
If jigasi doesn't receive a response to its REGISTER it will retry and this can be the reason you see multiple REGISTER without AUTH header. 
Do you have pcap files in /var/log/jitsi/jigasi/log/ they will have sent and received packets?

**Comment by jonaslindblom** [comment]
The pcap files seem to contain only the REGISTER and not the responses, so you are probably on the right track with your suspicion.

I tried to explicitly forward udp 5060 to my Jigasi box without success ... but I see in the VIA field of the response that it uses 10.0.2.15, which is a bridged adapter (not addressable on my LAN) on the Jigasi box (which is running in VirtualBox) ... maybe that is related.

It is btw not possible to run the SIP signalling over TCP instead? Would probably remove the above issue ..?

**Comment by jonaslindblom** [comment]
Yes, that is probably true. Anyways, this all makes more sense now. Many thanks for your input and fast response!

**Comment by jonaslindblom** [comment]
Indeed, making sure udp 5060 can make it back to Jigasi fixes the REGISTER problem.

Now running the Jitsi components in AWS, Jigasi can successfully REGISTER with FreeSWITCH (on another AWS box). I am trying to make inbound calls (from FreeSWITCH to Jigasi), but what I can see in the SIP-traces, is that FreeSWITCH tries to send the INVITES towards the internal interface IP of the Jigasi AWS box ... 

I also see that Jigasi puts this internal IP in the SIP Via header of the inital REGISTER.

I suspect I need to tell Jigasi explicitly somehow what the internal / external AWS IPs are? Similar to how the Videobridge is configured using the org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS / org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS settings?

**Comment by damencho** [comment]
This is not possible. We expect the server to support nats using latching. It sends everything where it gets it from. In asterisk this used to be an option where you enable nat for the account. I think and Freeswitch has similar option.

**Comment by jonaslindblom** [comment]
That is probably similar to setting "sip-force-contact" to "NDLB-connectile-dysfunction" in FreeSWITCH. I tried that and am now able to call in to a Jitsi conference basically using the original configuration generated by the installer. So it was all just configuration issues in the end. Closing this issue. Thanks again for your advice.
